### ISSUE TITLE
Deploy documentation

### ISSUE THREAD

**Issue by adriengoeller** [phlowers/mechaphlowers#9]
### Describe the expected behavior

Setup CI with [that link](https://squidfunk.github.io/mkdocs-material/publishing-your-site/)
Setup CD with [github pages](https://www.mkdocs.org/user-guide/deploying-your-docs/)

**Comment by ai-qui** [comment]
As discussed together, we'll try and deploy on readthedocs.io instead

**Comment by ai-qui** [comment]
Required steps to deploy the documentation on readthedocs.io:
- [ ] adapt the files in the repository (cf. https://docs.readthedocs.io/en/stable/intro/mkdocs.html)
- [ ] create an account on readthedocs.io
- [ ] point this account to mechaphlowers Github repository

The deployed documentation should then be updated each time we push new commits to this repository.
